### ISSUE TITLE
Remove docker/container packages from non-experimental branches

### ISSUE THREAD

**Issue by ealmonte32** [Screenly/screenly-ose#1382]
This is in reference to this closed PR: https://github.com/Screenly/screenly-ose/issues/1289

I have tried to write some ansible facts to gather this info in order to then use it to remove the packages, but was running into an issue since the commands to execute were giving me problems since I am not that good at ansible playbook, I think it was just easier for me in the bash install script since i am much better with that plus it is very simple and clean:

```
# users who chose experimental and then reverted back to master or production need docker removed
if [ "$BRANCH" != "experimental" ]; then
	sudo apt-get purge -y docker-ce docker-ce-cli containerd.io > /dev/null
fi
```

This was the ansible facts that I created:
```
pi@rpi3blk:~ $ cat /etc/ansible/facts.d/ose_branch.fact 
#!/bin/bash

# we create custom fact to always have a branch when ansible gathers
# this assigns the current branch to OSE_BRANCH variable
# we than call it when we need to

OSE_BRANCH=$(git -C /home/pi/screenly rev-parse --abbrev-ref HEAD)
echo "{\"Screenly OSE Branch\" : \"${OSE_BRANCH}\"}"
```

When tested gathering facts I got this:
```
pi@rpi3blk:~ $ ansible all -m setup -a 'filter=ansible_local'
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_local": {
            "ose_branch": {
                "Screenly OSE Branch": "master"
            }
        }, 
        "discovered_interpreter_python": "/usr/bin/python"
    }, 
    "changed": false
}
```
Maybe someone with more experience with ansible playbook can use that to write something like:
```
- name: Remove docker/containerd when not Experimental branch
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: absent
  when: "Screenly OSE Branch" is experimental
```
