### ISSUE TITLE
enable_ssl.sh hangs on Installs Nginx

### ISSUE THREAD

**Issue by friendfrog** [Screenly/screenly-ose#1510]
#### Overview of the Issue

I'm trying to create a secure connection to the Web Interface of Screenly on a few devices, whenever I run the script to enable ssl it runs fine at first but then hangs at Installs Nginx. After some time passed I cancelled the script with Ctrl+C and it seems like it goes through the rest of the script, but it doesn't change anything.
![cmd_2021-03-22_09-39-35](https://user-images.githubusercontent.com/55005591/112025965-fa3db980-8af2-11eb-99f3-1fbadd5e59f4.png)
#### Reproduction Steps

Connect to screenly over ssh
type sh /screenly/bin/enable_ssl.sh
watch the script hang at installs Nginx

#### Environment

* Raspberry Pi Hardware Version: Pi 3B+
* Raspberry Pi Network Setup: Ethernet
* Screenly OSE Version: production@d12df55

**Comment by ealmonte32** [comment]
I just tested this on a Pi3B and works fine..
Have you restarted the Pi? why would your apt be busy during this operation? if it's busy and you get a fail, the script wont execute and nginx-light package wont be installed, and that causes the playbook to fail..


These are all the steps that go through that playbook:
```
pi@transparentpi:~ $ cat ./screenly/ansible/roles/ssl/tasks/main.yml 
---
- name: Check screenly.conf
  command: cat /home/pi/.screenly/screenly.conf
  register: config
  tags:
    - enable-ssl

- set_fact: no_use_ssl_parameter="{{config.stdout.find('use_ssl') == -1}}"
  tags:
    - enable-ssl

- name: Installs Nginx
  apt:
    name: nginx-light
    state: present
    update_cache: yes
  tags:
    - enable-ssl

- name: Cleans up default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - enable-ssl

- name: Installs nginx config
  copy:
    src: nginx.conf
    dest:  /etc/nginx/sites-enabled/screenly.conf
    mode: 644
    owner: root
    group: root
  notify:
    - restart-nginx
  tags:
    - enable-ssl

- name: Installs self-signed certificates
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/{{ item }}"
    mode: 0600
    owner: root
    group: root
    force: no
  with_items:
    - screenly.crt
    - screenly.key
  tags:
    - enable-ssl

- name: Turn on the ssl mode
  lineinfile:
    dest: /home/pi/.screenly/screenly.conf
    insertafter: '^.*database.*'
    regexp: '^.*database.*;'
    line: 'use_ssl = True'
  tags:
    - enable-ssl
  when: no_use_ssl_parameter

- name: Turns on the ssl mode
  replace:
    replace: 'use_ssl = True'
    regexp: '^.*use_ssl.*'
    dest: /home/pi/.screenly/screenly.conf
  tags:
    - enable-ssl
  when: not no_use_ssl_parameter

- name: Modifies screenly-web service to only listen on localhost
  lineinfile:
    regexp: '^.*LISTEN.*'
    state: absent
    dest: /etc/systemd/system/screenly-web.service
  notify:
    - reload systemctl
    - restart-screenly-websocket_server_layer
    - restart-screenly-server
  tags:
    - enable-ssl
```
